In [1]:
import numpy as np

In [4]:

x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print (x)
print ("*"*50)
print (y)

数组的合并与拆分
[[1 2 3]
 [4 5 6]]
**************************************************
[[ 7  8  9]
 [10 11 12]]


In [8]:
print ("数组的合并与拆分")
print(np.concatenate([x,y],axis=1))
print(np.concatenate([x,y]))

数组的合并与拆分
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
x+y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
print ("垂直stack和水平stack")
print (np.vstack([x,y])) #相当于垂直组合
print (np.hstack((x,y)))#相当于水平组合

垂直stack和水平stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [16]:
print(np.split(ary=x,indices_or_sections=2))


[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [17]:
print(np.split(ary=x,indices_or_sections=3,axis=1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [18]:
print(x.repeat(2))

[1 1 2 2 3 3 4 4 5 5 6 6]


In [19]:
print(x.repeat(2,axis=1))

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [20]:
print(x.repeat(2,axis=0))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [22]:
print (np.tile(A=x,reps=3))

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [24]:
5+int('4')

9

In [25]:
06

SyntaxError: invalid token (<ipython-input-25-76b01ce73ac5>, line 1)

In [26]:
a=3
b=['f','mm',a,[1]]
b

['f', 'mm', 3, [1]]

In [27]:
cat_names = ['Walter', 'Ra']
dog_names = ['Joker', 'Simon', 'Ellie', 'Lishka', 'Fido']
horse_names = ['Mr. Ed']
animal_names = [cat_names, dog_names, horse_names]
animal_names

[['Walter', 'Ra'], ['Joker', 'Simon', 'Ellie', 'Lishka', 'Fido'], ['Mr. Ed']]

In [32]:
list(i for i in animal_names[1])

['Joker', 'Simon', 'Ellie', 'Lishka', 'Fido']

In [33]:
k=' b a'


In [35]:
k.split(sep=' ')

['ba']

In [36]:
kk=['a','b','C',1]

In [39]:
kk.remove('b')

In [40]:
kk

['a', 'C', 1]

In [41]:
kk.remove(1)

In [42]:
kk

['a', 'C']

In [43]:
kk.append([1,2])
kk

['a', 'C', [1, 2]]

In [44]:
animal={}

In [45]:
animal['kk']=1
animal

{'kk': 1}

In [46]:
animal['houzi']='monkey'
animal

{'houzi': 'monkey', 'kk': 1}

In [47]:
list(animal)

['kk', 'houzi']

In [54]:
for key,value in enumerate(list(animal)):
    print (key)
    print (value)
   

0
kk
1
houzi


In [50]:
animal

{'houzi': 'monkey', 'kk': 1}

In [55]:
type(animal)

dict

In [58]:
type(5.)

float

In [59]:
dir(animal)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [62]:
import pandas as pd

In [64]:
data=pd.Series(animal)

In [65]:
dir(data)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 

In [68]:
help(data.drop)

Help on method drop in module pandas.core.generic:

drop(labels, axis=0, level=None, inplace=False, errors='raise') method of pandas.core.series.Series instance
    Return new object with labels in requested axis removed.
    
    Parameters
    ----------
    labels : single label or list-like
    axis : int or axis name
    level : int or level name, default None
        For MultiIndex
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and existing labels are dropped.
    
        .. versionadded:: 0.16.1
    
    Returns
    -------
    dropped : type of caller

