In [19]:
import numpy as np
a=np.ones((3,2),dtype=np.float32)

In [25]:
a.ravel('F')

array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [22]:
a.flatten()

array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [5]:
a=[1,2,3]
b=a
b.append(4)
b

[1, 2, 3, 4]

In [7]:
a=[1,2,3]
for i in a:
    print ("the number is %r"%i) 
    b=i

the number is 1
the number is 2
the number is 3


In [10]:
type(b)

int

In [13]:
b=[]
for j in a:
    b.append(j)
    b

In [14]:
b

[1, 2, 3]

In [18]:
i=0
number=[]
while i <=6:
    print("the number is %r"%i)
    number.append(i)
    i+=2
print(number)

the number is 0
the number is 2
the number is 4
the number is 6
[0, 2, 4, 6]


第一节课程是什么

# 大的题目

In [23]:
%timeit b=[a**5 for a in range(100)]

10000 loops, best of 3: 66.6 µs per loop


In [24]:
b

[1, 2, 3]

In [28]:
b=[a**5 for a in range(100)]
b

[0,
 1,
 32,
 243,
 1024,
 3125,
 7776,
 16807,
 32768,
 59049,
 100000,
 161051,
 248832,
 371293,
 537824,
 759375,
 1048576,
 1419857,
 1889568,
 2476099,
 3200000,
 4084101,
 5153632,
 6436343,
 7962624,
 9765625,
 11881376,
 14348907,
 17210368,
 20511149,
 24300000,
 28629151,
 33554432,
 39135393,
 45435424,
 52521875,
 60466176,
 69343957,
 79235168,
 90224199,
 102400000,
 115856201,
 130691232,
 147008443,
 164916224,
 184528125,
 205962976,
 229345007,
 254803968,
 282475249,
 312500000,
 345025251,
 380204032,
 418195493,
 459165024,
 503284375,
 550731776,
 601692057,
 656356768,
 714924299,
 777600000,
 844596301,
 916132832,
 992436543,
 1073741824,
 1160290625,
 1252332576,
 1350125107,
 1453933568,
 1564031349,
 1680700000,
 1804229351,
 1934917632,
 2073071593,
 2219006624,
 2373046875,
 2535525376,
 2706784157,
 2887174368,
 3077056399,
 3276800000,
 3486784401,
 3707398432,
 3939040643,
 4182119424,
 4437053125,
 4704270176,
 4984209207,
 5277319168,
 5584059449,
 5

In [30]:
j=0
for i in b:
    j=j+i
j

161708332500

In [31]:
import numpy as np


In [32]:
a=np.arange(5)

In [33]:
a


array([0, 1, 2, 3, 4])

In [34]:
a=np.arange(20).reshape(2,10)

In [35]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
a.ndim

2

In [38]:
a.shape

(2, 10)

In [42]:
b=(np.zeros(10))
b

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [43]:
c=np.zeros_like(4)
c

array(0)

In [44]:
b.astype(int) #将变为类型

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
b[3:5]=7
b

array([ 0.,  0.,  0.,  7.,  7.,  0.,  0.,  0.,  0.,  0.])

In [46]:
d=a[7:9].copy()

In [47]:
d

array([], shape=(0, 10), dtype=int32)

In [48]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [49]:
a[0][2]

2

In [50]:
a[0,2]

2

In [51]:
a[a>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
a=np.random.randn(3,2,4)

In [54]:
a

array([[[ 0.92311126, -0.20834446,  1.03623757,  0.87503917],
        [-0.72043391, -1.35403374, -1.65249289,  0.41805351]],

       [[ 0.34554507,  1.92255225, -1.22614999, -3.02314647],
        [-1.31940771,  0.43173252,  0.51469426, -1.57080331]],

       [[-0.69076643, -2.63504703,  0.67332279,  0.07559099],
        [-0.63364859,  0.64688529,  0.48984203,  0.54484534]]])

In [55]:
a[a>0]

array([ 0.92311126,  1.03623757,  0.87503917,  0.41805351,  0.34554507,
        1.92255225,  0.43173252,  0.51469426,  0.67332279,  0.07559099,
        0.64688529,  0.48984203,  0.54484534])

In [57]:
a[a>0].shape

(13,)

In [58]:
a[a<0]=4

In [59]:
a

array([[[ 0.92311126,  4.        ,  1.03623757,  0.87503917],
        [ 4.        ,  4.        ,  4.        ,  0.41805351]],

       [[ 0.34554507,  1.92255225,  4.        ,  4.        ],
        [ 4.        ,  0.43173252,  0.51469426,  4.        ]],

       [[ 4.        ,  4.        ,  0.67332279,  0.07559099],
        [ 4.        ,  0.64688529,  0.48984203,  0.54484534]]])

In [65]:
aa=np.random.normal(size=(2,3))
aa

array([[-1.46315238,  0.21963639, -1.87318001],
       [-1.52239453, -0.5299757 , -0.03346764]])

In [67]:
data1=[3,4,8]
arr1=np.array(data1)
arr1

array([3, 4, 8])

In [72]:
arr1.astype(np.float16)

array([ 3.,  4.,  8.], dtype=float16)

In [75]:
data2=np.arange(1,9);data2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
data2.sum()

36

In [81]:
kk=np.array([a**3 for a in range(10)]).sum() #对列表中数据进行求和
kk

2025

In [82]:
np.array([a**3 for a in range(10)]).dtype

dtype('int32')

In [84]:
np.eye(3,2)

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [87]:
k=np.array([1,2],dtype=np.float32)

In [90]:
k=k.astype(int)

In [91]:
k.dtype

dtype('int32')

In [101]:
n_s=np.array([1.2,3.4,4])
n_s

array([ 1.2,  3.4,  4. ])

In [104]:
n_s=n_s.astype(k.dtype)

In [105]:
n_s.dtype

dtype('int32')

# 数组和标量之间的运算

In [107]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr*arr #大小相等的数组之间的任何算数运算都会将运算应用到元素级

array([[ 1,  4,  9],
       [16, 25, 36]])

In [116]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

数组于标量的算数运算会将那个标量值传播到各个元素中

In [114]:
arr-2 #数组与标量的算术运算也会将标量值传播到各个元素中

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [115]:
arr**0.2

array([[ 1.        ,  1.14869835,  1.24573094],
       [ 1.31950791,  1.37972966,  1.43096908]])

# 基本的索引和切片

In [118]:
arr=np.arange(10)

In [119]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
arr[5]  #索引

5

In [121]:
arr[5:8]

array([5, 6, 7])

In [124]:
arr[5:8]=99
arr  #对数组进行修改值，将一个标量值赋值给一个切片时，该值会自动传播到整个选区

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9])

In [128]:
arr_slice=arr[5:8] #切片视图
arr_slice[1]=200 #对切片视图中第1元素进行修改，并直接反映到源数组上
arr

array([  0,   1,   2,   3,   4,  99, 200,  99,   8,   9])

在一个二维数组中，各索引位置上的元素不再是标量而是一维数组

In [136]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d
#二维数组，也可采用arr3d=np.arange(1,10).reshape(3,3) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[1,2] #可以对各个元素进行递归访问，传入一个以逗号隔开的索引列表来选取单个元素

6

In [138]:
arr3d=np.arange(1,13).reshape(2,2,3) #3*3的数组
arr3d  #一个2*3的数组

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [139]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
#标量值和数组都可以被赋值给切片视图中
arr3d[0]=np.pi
arr3d

array([[[ 3,  3,  3],
        [ 3,  3,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr3d[0,1]=[11,12,25] #将数组赋值给切片视图
arr3d

array([[[ 3,  3,  3],
        [11, 12, 25]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# 切片索引

In [152]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr2d[:2,(0,2)] #对高纬度的数组进行切片索引；一次传入多个切片;这中索引得到相同维度的数组视图

array([[1, 3],
       [4, 6]])

In [154]:
arr2d[1,:2] #通过将整数索引和切片混合，可以得到低纬度的切片

array([4, 5])

In [156]:
arr2d[:,:2] #只有单独的冒号，表示选取整个轴

array([[1, 2],
       [4, 5],
       [7, 8]])

# 布尔型索引

In [170]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [171]:
data=np.random.random(size=(7,4))
data

array([[ 0.32750986,  0.55744922,  0.05160425,  0.37349814],
       [ 0.07137682,  0.79536905,  0.94703064,  0.21177272],
       [ 0.11815709,  0.14947179,  0.93736616,  0.38181976],
       [ 0.03069174,  0.29195411,  0.22178762,  0.45471375],
       [ 0.40689589,  0.5788001 ,  0.72581676,  0.29875256],
       [ 0.85678632,  0.70585204,  0.89748924,  0.84625042],
       [ 0.99356999,  0.96228167,  0.96258084,  0.55159061]])

In [172]:
names=='Bob' #生成布尔运算值
data[names=='Bob'] #通过布尔运算的值进行切片筛选

array([[ 0.32750986,  0.55744922,  0.05160425,  0.37349814],
       [ 0.03069174,  0.29195411,  0.22178762,  0.45471375]])

In [183]:
kkk=data[names=='Bob'][:,2] #布尔运算与整数索引混合使用
kkk

array([ 0.05160425,  0.22178762])

In [186]:
data[(names=='Bob')|(names=='Will')] #运用多个布尔条件，使用括号()不是中括号[]

array([[ 0.32750986,  0.55744922,  0.05160425,  0.37349814],
       [ 0.11815709,  0.14947179,  0.93736616,  0.38181976],
       [ 0.03069174,  0.29195411,  0.22178762,  0.45471375],
       [ 0.40689589,  0.5788001 ,  0.72581676,  0.29875256]])

In [189]:
data[(names=='Bob')&(names!='Will')] # 布尔运算符&（且），|(或)，！（否），且关键字and 和or 在布尔型数组中无效

array([[ 0.32750986,  0.55744922,  0.05160425,  0.37349814],
       [ 0.03069174,  0.29195411,  0.22178762,  0.45471375]])

In [192]:
#通过布尔运算进行设置值
data[names=='Bob']=10
data

array([[ 10.        ,  10.        ,  10.        ,  10.        ],
       [  0.07137682,   0.79536905,   0.94703064,   0.21177272],
       [  0.11815709,   0.14947179,   0.93736616,   0.38181976],
       [ 10.        ,  10.        ,  10.        ,  10.        ],
       [  0.40689589,   0.5788001 ,   0.72581676,   0.29875256],
       [  0.85678632,   0.70585204,   0.89748924,   0.84625042],
       [  0.99356999,   0.96228167,   0.96258084,   0.55159061]])

# 花式索引：利用整数数组进行索引

In [194]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [195]:
arr[[4,3,0,6]] #整数进行索引

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [196]:
arr[[-3,-5,-7]] #使用负数进行从末尾开始取值

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [198]:
#一次传入多个索引数组，返回的是一个一维数组
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [199]:
arr[[1,5,7],[0,3,2]] #返回一维数组，最终选取的元素时（1，0），（5，3），（7，2）

array([ 4, 23, 30])

In [203]:
arr[[1,5,7]][:,[0,3,1,2]] #[0,3,1,2]是输出的顺序

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30]])

# 数组转置和轴对换

In [204]:
arr.T #数组转置

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [206]:
np.dot(arr.T,arr) #矩阵内积

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

# 通用函数：快速的元素级数组函数

一组对ndarry中的数据执行元素级运算的函数

In [210]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [211]:
np.sqrt(arr) #一元函数ufunc

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479],
       [ 3.46410162,  3.60555128,  3.74165739,  3.87298335],
       [ 4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152],
       [ 4.89897949,  5.        ,  5.09901951,  5.19615242],
       [ 5.29150262,  5.38516481,  5.47722558,  5.56776436]])

In [214]:
x=np.random.randn(8)
y=np.random.randn(8)
x,y

(array([ 1.98820228, -0.01925783,  0.22699873,  0.24495563, -1.46278512,
         0.79506202,  0.70016653,  0.04414157]),
 array([ 0.80497652,  0.09721362,  0.64073859, -0.51219419, -1.59100751,
        -0.9503367 ,  0.56174906,  0.28249587]))

In [215]:
np.maximum(x,y) #元素级最大值

array([ 1.98820228,  0.09721362,  0.64073859,  0.24495563, -1.46278512,
        0.79506202,  0.70016653,  0.28249587])